skip_processing:
  - README.md
  - config.yaml
  - install
  - install.ps1
linux:
  skip_processing: []
  powershell:
    - ~/.config/powershell
  tmux: ~/.config/tmux
windows:
  skip_processing:
    - zshrc
  powershell:
    - "%MYDOCUMENTS%/WindowsPowerShell"
    - "%MYDOCUMENTS%/PowerShell"
