skip_processing:
  - README.md
  - config.yaml
  - install
  - install.ps1
linux:
  skip_processing: []
  nvim: ~/.config/nvim
  powershell: ~/.config/powershell
  tmux: ~/.config/tmux
windows:
  skip_processing:
    - zshrc
  nvim: "%LOCALAPPDATA%/nvim"
  powershell:
    - "%MYDOCUMENTS%/WindowsPowerShell"
    - "%MYDOCUMENTS%/PowerShell"
